packages:
  - apps/*
  - packages/*

catalog:
  "@prettier/plugin-oxc": ^0.0.4
  "@types/node": ^24.7.2
  oxlint: ^1.23.0
  oxlint-tsgolint: ^0.5.1
  prettier: ^3.6.2
  typescript: ^5.9.2

catalogMode: strict

catalogs:
  api:
    "@fastify/autoload": ^6.3.1
    "@fastify/sensible": ^6.0.3
    concurrently: ^9.2.1
    fastify: ^5.6.1
    fastify-cli: ^7.4.0
    fastify-plugin: ^5.1.0
    fastify-tsconfig: ^3.0.0
    tsdown: ^0.15.7
  web:
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    "@vitejs/plugin-react": ^5.1.0
    react: ^19.2.0
    react-dom: ^19.2.0
    vite: npm:rolldown-vite@7.2.2

overrides:
  vite: npm:rolldown-vite@7.2.2

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 1440
